# Generated by Django 5.2.2 on 2025-06-12 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tecnico_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
