# Generated by Django 5.2.2 on 2025-06-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_ordenservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='comentario_final',
            field=models.TextField(blank=True, null=True),
        ),
    ]
